import localFont from "next/font/local";
import "./ui/globals.css";
import Image from 'next/image';
import Logo from "/public/BienalLogo.png";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }){
    return (
        <html lang="en">
            <body>
            <header>
                <Image src={Logo} alt = "Bienal Logo" />
                <div>
                    <h1>Bienal del Chaco</h1>
                    <p>Por amor al arte</p>
                </div>
            </header>
              {children}
              <footer>
                  <p>© 2021 Bienal del Chaco</p>
              </footer>
              </body>
        </html>
    );
}